# Generated by Django 3.2.9 on 2022-01-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order_info',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order_info',
            name='name',
            field=models.CharField(default=' Test01', max_length=50),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='address',
            field=models.CharField(default=' Test01', max_length=250),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='city',
            field=models.CharField(default=' TPE', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='email',
            field=models.EmailField(default=' jeyu54217@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='postal_code',
            field=models.CharField(default=' 000', max_length=20),
        ),
    ]
